import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Providers } from "@/lib/providers";
import "./globals.css";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "PetsPaw",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" app-theme="dark">
      <body className={`${jost.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
