import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import { Providers } from '@/app/lib/providers';
import '@/app/globals.css';

const jost = Jost({
  subsets: ['latin'],
  variable: '--font-jost'
});

export const metadata: Metadata = {
  title: 'PetsPaw',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en" app-theme="light">
        <body className={`${jost.className} antialiased`}>{children}</body>
      </html>
    </Providers>
  );
}
